export const LOAD_COMMENTS = "LOAD_COMMENTS";

export const COMMENTS_LOADING = "COMMENTS_LOADING";

export const ADD_COMMENT = "ADD_COMMENT";

export const COMMENTS_FAILED = "COMMENTS_FAILED";

export const GALLERIES_LOADING = "GALLERIES_LOADING";

export const LOAD_GALLERIES = "LOAD_GALLERIES";

export const GALLERIES_FAILED = "GALLERIES_FAILED";

export const CATEGORIES_LOADING = "CATEGORIES_LOADING";

export const LOAD_CATEGORIES = "LOAD_CATEGORIES";

export const CATEGORIES_FAILED = "CATEGORIES_FAILED";

export const ADD_LOGGED_USER = "ADD_LOGGED_USER";

export const LOAD_LOGGEDIN_USER = "LOAD_LOGGEDIN_USER";

export const LOGGEDIN_USER_FAILED = "LOGGEDIN_USER_FAILED";
export const LOGOUT_USER = "LOGOUT_USER";
export const LOGOUT_USER_FAILED = "LOGOUT_USER_FAILED";